apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dcex
  namespace: default
spec:
  secretName: dcex-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: dcex.krishdev.xyz
  dnsNames:
  - dcex.krishdev.xyz