apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcex
  labels:
    app: dcex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dcex
  template:
    metadata:
      labels:
        app: dcex
    spec:
      containers:
        - name: dcex
          image: krishanand01/dcex:v2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: env
      volumes:
        - name: env-file
          secret:
            secretName: dcex-secret