apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - DCEX.krishdev.xyz
      secretName: DCEX-tls

  rules:
    - host: DCEX.krishdev.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcex
                port:
                  number: 80
