apiVersion: v1
kind: Service
metadata:
  name: dcex
  namespace: dcex
  labels:
    app: dcex
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: dcex